### PR TITLE
Add some missing awaits and catch calls

### PR DESCRIPTION
**Pull request by geisterfurz007**
There are still some instances where YesBot restarts on errors deleting messages so this PR adds some awaits and catch clauses in places where messages are deleted so it's not a problem if a user deletes their message faster than YesBot can.

### CODE REVIEW

**Comment by hasanlatch007** [comment]
Missing linting

**Review by hasanlatch007 — APPROVED** [review]
Couldn't spot any more missing catch and awaits. LGTM!

**Comment by hasanlatch007** [comment]
Requires rebase

**Comment by geisterfurz007** [comment]
> Couldn't spot any more missing catch and awaits. LGTM!

Oh WebStorm spotted plenty but the most recent crashes seemed to have been caused by errors in `Message#delete` calls, so those were my priority here. We can clean up the rest slowly but surely. The problematic ones will be easy to spot soon once null safety isn't an issue anymore!

> Requires rebase

Done; merging then :)

**Comment by hasanlatch007** [comment]
> > Couldn't spot any more missing catch and awaits. LGTM!
> 
> Oh WebStorm spotted plenty but the most recent crashes seemed to have been caused by errors in `Message#delete` calls, so those were my priority here. We can clean up the rest slowly but surely. The problematic ones will be easy to spot soon once null safety isn't an issue anymore!
> 
> > Requires rebase
> 
> Done; merging then :)

Should probably start using WebStorm then, I was going through major files 👀

**Pull request merged**
