### PR TITLE
Chore: Rewrite dm menu

### PR DESCRIPTION
**Pull request by hasanlatch007**
Moved everything necessary from `message.ts` and with the `trigger: "!menu"` this technically should not break if was meant for a game :)

### CODE REVIEW

**Comment by hasanlatch007** [comment]
For some reasons this merged the polls commits and dm commits :') ill fix it later

**Comment by geisterfurz007** [comment]
You probably created the branch from the polls branch and not from master :) Polls are merged, so if you rebase now, things should be better.

**Comment by hasanlatch007** [comment]
I hate this.

**Comment by hasanlatch007** [comment]
im fucking done with this branch im rewriting the whole code idc

**Pull request closed without merging**
